spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/librarian?useSSL=false&autoReconnect=true&jdbcCompliantTruncation=false
    username: root
    password: root

logging:
  level:
    .: WARN
    xp.librarian: INFO